DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS REGISTRATIONS;
DROP TABLE IF EXISTS LECTURES;

CREATE TABLE USERS (
    id UUID PRIMARY KEY,
    login VARCHAR(50) NOT NULL,
    email VARCHAR(320) NOT NULL
);


CREATE TABLE LECTURES (
                          id UUID PRIMARY KEY,
                          topic VARCHAR(100) NOT NULL,
                          startTime VARCHAR(5) NOT NULL,
                          availablePlaces INT NOT NULL
);

CREATE TABLE REGISTRATIONS (
    id UUID PRIMARY KEY,
    userId UUID NOT NULL,
    lectureId UUID NOT NULL,
    FOREIGN KEY (userId) REFERENCES USERS(id),
    FOREIGN KEY (lectureId) REFERENCES LECTURES(id)
);
